### ISSUE TITLE
Jenkins failed to launch the agent process

### ISSUE THREAD

**Issue by thirupathi444** [QT-DevOps/AzureIssues#84] opened 2020-05-23 18:17 UTC
while launching the agents the fallowing errors were occurred . please suggest me  
1.for known host file  verification strategy 

the fallowing error occurred please find the attached 

/var/lib/jenkins/.ssh/known_hosts [SSH] No Known Hosts file was found at /var/lib/jenkins/.ssh/known_hosts. Please ensure one is created at this path and that Jenkins can read it.
Key exchange was not finished, connection is closed.
================================================================
2.non verifying verification strategy

java.io.IOException: Could not copy remoting.jar into '/home/jenkins/test' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:715)
	at hudson.plugins.sshslaves.SSHLauncher.access$300(SSHLauncher.java:112)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:455)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not copy remoting.jar to '/home/jenkins/test/remoting.jar' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:707)
	... 7 more
Caused by: com.trilead.ssh2.SFTPException: Permission denied (SSH_FX_PERMISSION_DENIED: The user does not have sufficient permissions to perform the operation.)
	at com.trilead.ssh2.SFTPv3Client.openFile(SFTPv3Client.java:1201)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1074)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1055)
	at com.trilead.ssh2.jenkins.SFTPClient.writeToFile(SFTPClient.java:102)
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:700)
	... 7 more
[05/23/20 18:13:10] Launch failed - cleaning up connection
[05/23/20 18:13:10] [SSH] Connection closed.

**Comment by srmanikanta** [comment] 2020-05-24 03:16
hi thirupathi, please follow this instructions:

first login into jenkins master and then switch as jenkins user.
```
sudo -i
su  jenkins
cd ~
```
once the switched to jenkins user please try to login with node credentainls
`ssh <nodeusername>@<nodeuserprivateip>`
goto manage jenkins-> manage node-> configure the node

once the node configuration is done launch the agent.
Note: *  Before doing the above configuration
          * check the user is added in visudo and enable password authentication is yes for jenkins node.
         * restart the sshd service

please close the issue.

**Comment by thirupathi444** [comment] 2020-05-24 04:25
hi manikanta even i am getting error i have done what u have suggest 
java.io.IOException: Could not copy remoting.jar into '/home/jenkins/test' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:715)
	at hudson.plugins.sshslaves.SSHLauncher.access$300(SSHLauncher.java:112)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:455)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not copy remoting.jar to '/home/jenkins/test/remoting.jar' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:707)
	... 7 more
Caused by: com.trilead.ssh2.SFTPException: Permission denied (SSH_FX_PERMISSION_DENIED: The user does not have sufficient permissions to perform the operation.)
	at com.trilead.ssh2.SFTPv3Client.openFile(SFTPv3Client.java:1201)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1074)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1055)
	at com.trilead.ssh2.jenkins.SFTPClient.writeToFile(SFTPClient.java:102)
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:700)
	... 7 more
[05/24/20 04:23:07] Launch failed - cleaning up connection
[05/24/20 04:23:07] [SSH] Connection closed.

**Comment by rawatssns** [comment] 2020-05-24 04:36
1. make sure connectivity betn both nodes
2. ssh the 2nd node from master, it will ask you whether it is trusted?
3. Just say "yes"
4. Enter the password
5. then i will be add to Known_host file

**Comment by thirupathi444** [comment] 2020-05-24 05:09
i have done the login to to the remote machine from Jenkins masters user and i can successfully login in to that now i create a file called "test"  in remote machine /home/jenkins/test. now the error is occurred like bellow  

SSHLauncher{host='100.25.153.148', port=22, credentialsId='jenkins', jvmOptions='', javaPath='',
 prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.KnownHostsFileKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[05/24/20 05:03:36] [SSH] Opening SSH connection to 100.25.153.148:22.
Searching for 100.25.153.148 in /var/lib/jenkins/.ssh/known_hosts
Searching for 100.25.153.148:22 in /var/lib/jenkins/.ssh/known_hosts
[05/24/20 05:03:36] [SSH] SSH host key matches key in Known Hosts file. Connection will be allowed.
[05/24/20 05:03:36] [SSH] Authentication successful.
[05/24/20 05:03:37] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="4" [2]="20" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.4.20(1)-release'
DIRSTACK=()
EUID=1001
GROUPS=()
HOME=/home/jenkins
HOSTNAME=ip-172-31-52-144
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=C.UTF-8
LOGNAME=jenkins
MACHTYPE=x86_64-pc-linux-gnu
MAIL=/var/mail/jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PIPESTATUS=([0]="0")
PPID=1385
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='18.234.169.15 51666 22'
SSH_CONNECTION='18.234.169.15 51666 172.31.52.144 22'
TERM=dumb
UID=1001
USER=jenkins
XDG_RUNTIME_DIR=/run/user/1001
XDG_SESSION_ID=3
_=']'
[05/24/20 05:03:37] [SSH] Checking java version of /home/jenkins/test/jdk/bin/java
Couldn't figure out the Java version of /home/jenkins/test/jdk/bin/java
bash: /home/jenkins/test/jdk/bin/java: No such file or directory

[05/24/20 05:03:37] [SSH] Checking java version of java
[05/24/20 05:03:37] [SSH] java -version returned 1.8.0_252.
[05/24/20 05:03:37] [SSH] Starting sftp client.
[05/24/20 05:03:37] [SSH] Copying latest remoting.jar...
java.io.IOException: Could not copy remoting.jar into '/home/jenkins/test' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:715)
	at hudson.plugins.sshslaves.SSHLauncher.access$300(SSHLauncher.java:112)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:455)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not copy remoting.jar to '/home/jenkins/test/remoting.jar' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:707)
	... 7 more
Caused by: com.trilead.ssh2.SFTPException: Permission denied (SSH_FX_PERMISSION_DENIED: The user does not have sufficient permissions to perform the operation.)
	at com.trilead.ssh2.SFTPv3Client.openFile(SFTPv3Client.java:1201)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1074)
	at com.trilead.ssh2.SFTPv3Client.createFile(SFTPv3Client.java:1055)
	at com.trilead.ssh2.jenkins.SFTPClient.writeToFile(SFTPClient.java:102)
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:700)
	... 7 more
[05/24/20 05:03:38] Launch failed - cleaning up connection
[05/24/20 05:03:38] [SSH] Connection closed.
connect timed out

**Comment by rawatssns** [comment] 2020-05-24 06:00
this issue sometime related to Permission. request you to check the user permission on the folder & group 

Caused by: java.io.IOException: **Could not copy remoting.jar to '/home/jenkins/test/remoting.jar' on agent**
at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:707)
... 7 more
Caused by: com.trilead.ssh2.SFTPException: **Permission denied** (SSH_FX_PERMISSION_DENIED: The user does not have sufficient permissions to perform the operation.)

**Comment by srmanikanta** [comment] 2020-05-24 08:14
hi tirupathi, 
follow this apparoach
## node configuration
1. first in first connect your node 
2. create a user on jenkins node command is
`adduser jenkins` //you have to change the username jenkins to some other name
// set the password if you are using ubuntu it will automatically asks password whenever you execute adduser comman but if you are using centos manually you have to set the password
by executing the command `passwd jenkins`
3. then add the user in to /etc/sudoers file. command is
`visudo`
once the file is opened then add the find this line`root   ALL=(ALL:ALL) ALL`
add this line to below 
`jenkins   ALL=(ALL:ALL) NOPASSWD:ALL`
4. open this file `sudo vi /etc/ssh/sshd_config`
find the line `passwordauthentication no`
set as `passwordauthentication yes` // just change no to yes.
5. restart the jenkins command is 
`sudo service sshd restart`

## jenkins server  configuration
1.connect to your jenkins server 
2. switch as jenkins user, execute the below commands
```
sudo -i
su jenkins
cd ~
```
3. now connect to jenkins node from jenkins server
`ssh <nodeusername>@<nodeip>`
it will ask password enter that password. once connectef successfully then configure the node in jenkins 
4. go to manage jenkins --> manage nodes-> add node please provide a validate details
5. relaunch the node.

This is the complete process I think this is useful to you if not please ignore.

**Comment by thirupathi444** [comment] 2020-05-24 09:14
thanks u somuch srmanikanta&rawatssns my problem is resolved

**Closed as completed** 2020-05-24 09:14 UTC
